image: node:alpine
cache:
  paths:
    - node_modules/
    - app/bower_components
deploy:
  stage: deploy
  environment: prod
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install
    - bower install --allow-root
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
